### ISSUE TITLE
Units for the variable

### ISSUE THREAD

**Issue by nadarbreicq** [tinkersprojects/Delta-Kinematics-Library#1]
Hello ! 

First thank you for your job ! As I'm building a delta robot with servo, it will help me a lot ! But I have some questions about the unit you use into you functions and the meaning of the variables. So : 
- What is the units for the variables : ```ArmLength | RodLength | BassTri | PlatformTri ``` ? mm ? cm ?
- What is the meaning of ```BassTri``` and ```PlatformTri``` ? Maybe a little drawing could help ?

Maybe it could help to add these informations into your readme ? 

Thank you in advance !

**Comment by tinkersprojects** [comment]
Hey, sorry I thought i had replied to this.
I have been working on this on and off between all my other projects

The units could be any units as long as they are consistent since the library uses trigonometry But there are some problems with using Millimetre. I found the best way to use Meters, I have updated the examples.

BassTri and PlatformTri, yea I will put a picture up explaining it a bit more and update the readme

thanks 
if you have any other concerns, just let me know.

**Comment by roydekleijn** [comment]
Can you please elaborate how I can measure BassTri and PlatformTri ? It will be helpful if you can mark it in a drawing

**Comment by tinkersprojects** [comment]
Hey sorry for taking Soo long to get updates through. I have been busy working on other things. I have done images but there more confusing than anything and still thinking of better ways of doing it.
To get the BassTri and PlatformTri, imagen a line going through the pivot of the arms, you will find that they will intercept. this is the triangle. the sides of the triangle should be all equal making it an equilateral triangle. the length of the side or the distance from the center (one of them, just can't remember which one at the moment) is used for the BassTri. Then do the same for the Platform to get the PlatformTri.

**Comment by tinkersprojects** [comment]
Hey, I finally got time to do some work on this library.
i have done many improvements and have included a crapy drawing (its terrible)
it has a new set of calculations with forward and inverse kinematics of for the delta.

**Comment by DouglasPearless** [comment]
Awesome,

I will look at it next week 👍😄
